### ISSUE TITLE
Deploy action is performed even though PR is not approved

### ISSUE THREAD

**Issue by TrulyNotMalware** [TrulyNotMalware/Spring-Stack#6]
It should only work when PR is approved.

**Comment by TrulyNotMalware** [comment]
https://docs.github.com/ko/actions/using-workflows/events-that-trigger-workflows#pull_request

maybe
```yml
name: Prod-OAuth-Build
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
```
